import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";
import { AvatarImage } from "@radix-ui/react-avatar";
import { Button } from "@/components/ui/button";
import Link from "next/link";
import Heart from "@/components/icons/heart";
import GalleryIcon from "@/components/icons/gallery";
import Archive from "@/components/icons/archive";
import Folder from "@/components/icons/folder";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function SideMenu() {
  return (
    <div className="pb-12 w-1/5">
      <div className="space-y-4 py-4">
        <div className="px-3 py-2">
          <h2 className="mb-2 px-4 text-lg font-semibold tracking-tight">
            Manage
          </h2>
          <div className="space-y-1 flex gap-1 flex-col">
            <Link href="/gallery">
              <Button
                variant="secondary"
                className="w-4/5 justify-start flex gap-2 group"
              >
                <GalleryIcon />
                Gallery
              </Button>
            </Link>
            <Link href="/albums">
              <Button
                variant="secondary"
                className="w-4/5 justify-start flex gap-2 group"
              >
                <Folder />
                Albums
              </Button>
            </Link>
            <Link href="/archive">
              <Button
                variant="secondary"
                className="w-4/5 justify-start flex gap-2 group"
              >
                <Archive />
                Archive
              </Button>
            </Link>

            <Link href="/favorites">
              <Button
                variant="secondary"
                className="w-4/5 justify-start flex gap-2 group"
              >
                <Heart />
                Favorites
              </Button>
            </Link>
          </div>
        </div>
      </div>
    </div>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="border-b ">
          <div className="flex h-16 items-center px-4 container mx-auto">
            GALLERY APP
            {/* <TeamSwitcher />
            <MainNav className="mx-6" />*/}
            <div className="ml-auto flex items-center space-x-4">
              <Avatar>
                <AvatarImage src="https://github.com/shadcn.png" />
                <AvatarFallback>CN</AvatarFallback>
              </Avatar>{" "}
              {/* <Search />
              <UserNav /> */}
            </div>
          </div>
        </div>
        <div className="flex">
          <SideMenu />

          <div className="w-full pt-12 px-4">{children}</div>
        </div>
      </body>
    </html>
  );
}
